### ISSUE TITLE
catch version 2.13.4 building with glibc v2.35 causes a compiler error?

### ISSUE THREAD

**Issue by Thomashrb** [rdjondo/cplings#1]
I followed the instructions from the readme but the `make` step produced an error for me.

I found a github issue containing the same error message I saw:
https://github.com/catchorg/Catch2/issues/2421

bumping Catch2 by one minor version fixed the issue for me:

```
@@ -29,7 +29,7 @@ set(CPM_DOWNLOAD_LOCATION "cmake/CPM.cmake")
 include(${CPM_DOWNLOAD_LOCATION})
 
 # Specify dependencies
-CPMAddPackage("gh:catchorg/Catch2@2.13.4")
+CPMAddPackage("gh:catchorg/Catch2@2.13.5")
 
 # Including packages for safe_numerics
 CPMAddPackage(NAME safe_numerics
```

also thank you for making this :)

**Comment by rdjondo** [comment]
Hello, @Thomashrb, feel free to contribute to the repo with your fix by opening a Pull Request and I will merge it. Thank you🙏

**Comment by Thomashrb** [comment]
^ ok I opened a pr. I am new to PRs on github (and cpp) so if I did something wrong please let me know and I will be happy to fix my mistake.
