### ISSUE TITLE
Incorrect Order of Execution in CMakeLists for EXERCISES Set

### ISSUE THREAD

**Issue by rahul007-bit** [rdjondo/cplings#3]
## Issue Description:

Os in which i have tried MacOs and Debian.

The current order of execution defined in the EXERCISES variable set in the CMakeLists does not follow the expected sequence. The variables8 file is executed before the variables1 file, which is counter-intuitive.

#### Here is the current CMakeLists configuration:

``` cmake
set(EXERCISES
    variables8
    variables7
    variables6
    variables5
    variables4
    variables3
    variables2
    variables1
)
```
The expected behavior is to execute the exercises in ascending order, from variables1 to variables8. This order follows a logical progression and enhances the user experience.

#### Here is the proposed corrected sequence:

``` cmake
set(EXERCISES
    variables1
    variables2
    variables3
    variables4
    variables5
    variables6
    variables7
    variables8
)
```

**Comment by rdjondo** [comment]
Thanks, could you submit a Pull Request?

Raphael

**Comment by rahul007-bit** [comment]
Thank you for your reply, should I submit one PR for all other exercises, will it work?
